### ISSUE TITLE
Not working on C or C++ files

### ISSUE THREAD

**Issue by Mikaz-fr** [munyabe/ToggleComment#2]
The toggle command is not doing anything for .c, .cpp or .h files.

I believe this can be fix by expanding: https://github.com/munyabe/ToggleComment/blob/master/ToggleComment/ToggleCommentCommand.cs#l92

Instead of: `case "CSharp":`
Something like:
```
case "CSharp":
case "C":
case "CPlusPlus":
case "H":
```

I would have proposed a patch but for some reason I'm not able to open the project locally so I can't try it.

Could you please add support for these types of files ?

**Comment by Mikaz-fr** [comment]
Additionally, I believe that if you would rely on built-in commands "Comment Selection" and "Uncomment Selection" you would support anything VS supports, rather than having to re-implement things yourself.
Not fully sure it's possible though as I have to VS experience.

**Comment by munyabe** [comment]
Thanks for your feedback!
I'll support C, C++ and change the behavior of the files that it doesn't support.
Updated version will be released in a few days.

**Comment by Mikaz-fr** [comment]
Perfect, please let us know when available so I can try it out.

**Comment by munyabe** [comment]
I have made a new release now! Please update from gallery.

**Comment by Mikaz-fr** [comment]
Confirmed that this is working great with 1.2. And the error message on unknown format is helpful.

Thanks for the quick update.
