### ISSUE TITLE
Behaviour not as expected

### ISSUE THREAD

**Issue by s9w** [munyabe/ToggleComment#4]
When the lines are only partially selected, like this (before / after):

![img](http://i.imgur.com/62VhhI5.png)

The comments don't range the whole lines. That's not what the screenshot on the gallery suggests. Is this a bug or as intended?

**Comment by munyabe** [comment]
Sorry for my late reply. 
This is a bug. I was mistaken...
I'll fi it.

**Comment by munyabe** [comment]
This issue should be fixed at v1.3. Please update the extension.

**Comment by Ilias48rus** [comment]
Damn, how to return the block commenting ("/*","*/") ?
