### ISSUE TITLE
Compatibility VS 2017

### ISSUE THREAD

**Issue by Tagliatti** [munyabe/ToggleComment#6]
Hello, could I add VS 2017 compatibility? TKS

**Comment by kvart714** [comment]
+1

**Comment by rXc3NtR1c** [comment]
+1 also. I imagine it would only be adding this to the manifest:

```XML
<VisualStudio Version="15.0">
    <Edition>Enterprise</Edition>
    <Edition>Pro</Edition>
</VisualStudio>
```

**Comment by rXc3NtR1c** [comment]
Have opened a pull request for the required changes. Biggest change is the difference in manifest versions and subsequent differences.

**Comment by munyabe** [comment]
Sorry for being late.

Thanks for your nice pull request!
Updated version will be released ASAP.

**Comment by munyabe** [comment]
I have made a new release now !
