### ISSUE TITLE
ToggleComment not working on VS 2015 update 3

### ISSUE THREAD

**Issue by Giois93** [munyabe/ToggleComment#9]
After I install update 3 for VS 2015 toggle comment is not working. I can't see toggleComment features in Edit > Advanced nor in Keyboard options.

Tried disable and reinstall.

**Comment by munyabe** [comment]
Sorry for my late reply.
I tried to fix it. Can you check if the following module works?
https://github.com/munyabe/ToggleComment/releases/tag/v1.6.1

**Comment by Giois93** [comment]
It seems to work well.

Thankyou.
